#!/bin/bash
set -e

local_dir="$HOME/Downloads/CentOS6.updates/x86_64/Packages"
remote_dir="http://mirror.centos.org/centos/6/updates/x86_64/Packages/"
mirror_dir="/Volumes/SBT-Gorbunov-VV"

local=$(ls $local_dir | sort)
remote=$(curl -s $remote_dir \
  | ruby -n -e 'puts $_[/<a href="(.*\.rpm)">/,1]' | grep -v '^$' | sort)

comm -2 -3 <(printf "%s\n" ${remote}) <(printf "%s\n" ${local})

if [ "$1" == "-d" ]; then
  for file in $(comm -2 -3 <(printf "%s\n" ${remote}) <(printf "%s\n" ${local})); do
    echo "Download ${file}"
    curl -C - ${remote_dir}${file} -o ${local_dir}/${file}
    cp -v ${local_dir}/${file} ${mirror_dir}/${file}
  done
fi
