#!/bin/bash
set -e

local_dir="$HOME/Downloads/CentOS7.updates/x86_64/Packages"
remote_dir="http://mirror.centos.org/centos/7/updates/x86_64/Packages/"

local=$(ls $local_dir | sort)
remote=$(curl -s $remote_dir \
  | ruby -n -e 'puts $_[/<a href="(.*\.rpm)">/,1]' | grep -v '^$' | sort)

comm -2 -3 <(printf "%s\n" ${remote}) <(printf "%s\n" ${local})

[ "$1" == "-d" ] \
  && comm -2 -3 <(printf "%s\n" ${remote}) <(printf "%s\n" ${local}) \
  | xargs -I {} curl ${remote_dir}{} -o ${local_dir}/{}
